version: 2.1
orbs:
  node: circleci/node@6.1.0

executors:
    linux-docker:
        docker:
            - image: cimg/node:20.12.2
    macos:
        macos:
            xcode: 14.2.0
        resource_class: m2pro.medium.test
    macos-medium:
        macos:
            xcode: 14.2.0
        resource_class: macos.m1.medium.gen1
    # macos-medium-rosetta:
    #     macos:
    #         xcode: 14.2.0
    #     resource_class: macos.m1.medium.gen1
    #     shell: arch -x86_64 /bin/bash --login -c
    # macos-rosetta:
    #     macos:
    #         xcode: 14.2.0
    #     resource_class: macos.m1.large.gen1
    #     shell: arch -x86_64 /bin/bash --login -c

workflows:
  docker-mac-tests:
    jobs:
      - build-and-test:
          matrix:
            parameters:
              os: [macos-medium, macos]

jobs:
  build-and-test:
    parameters:
          os:
            type: executor
    executor: << parameters.os >>
    parallelism: 5
    working_directory: ~/test-electron
    steps:
      - checkout
      - run:
          name: Install ffmpeg
          command: brew install ffmpeg
      - node/install:
          install-yarn: true
          node-version: '20.12.2'
          yarn-version: '1.22.19'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate Builds
          command: yarn build
      # - run:
      #     name: Unclear if necessary (yarn make)
      #     command: yarn make
      - run:
          name: Generate Package
          command: yarn package
      - run:
          name: Test
          command: yarn test:singleremote
